version: "3.3"

services:
  ozet-hybrid-proxy:
    image: nginx:latest
    container_name: ozet-hybrid-proxy
    restart: "on-failure"
    ports:
      - 10431:10431
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  ozet-hybrid:
    image: ozetteam/ozet-hybrid
    container_name: ozet-hybrid
    restart: "on-failure"
    env_file:
      - "./.env"
    expose:
      - 3030
    stdin_open: true
    tty: true
